config/routes.rb
Rails.application.routes.draw do
  root to: "items#index"
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root to: "users#home"oooh
  resources :items do
    resources :bookings, :only => [:new, :create]
  end

  resources :bookings do
    resources :reviews, only: [ :new, :create ]
  end
  
  resources :bookings, :only => :index
  resources :users, :only => [:index, :show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_one :review
  belongs_to :item
  belongs_to :user
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :bookings
  paginates_per 12
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :items
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # skip_before_action :authenticate_user!, only: :home
    before_action :authenticate_user!
    

    def home
    end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    def index
        user = current_user
        @bookings = user.bookings
    end

    def new
        @item = Item.find(params[:item_id])
        @booking = Booking.new # needed to instantiate the fookingend
    end

    def create
        p booking_params
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.item_id = params[:item_id]
    @booking.save

    # no need for app/views/restaurants/create.html.erb
    redirect_to bookings_path
    end

    private

    def booking_params
        params.require(:booking).permit(:booking_start, :booking_end)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_item, only: [:show, :create, :edit]

  def index
      @items = Item.page params[:page]
  end

  def new
      @item = Item.new
  end

  def show
    @marker = User.geocoded.find(@item.user_id)
  end

  def create
      @item = Item.new(item_params)
      @item.user_id = current_user.id
      if @item.save
        redirect_to items_path(@items)
      else
        render :new
      end
  end

  def edit
  end

  private

  def item_params
    params.require(:item).permit(:picture_url, :price, :deposit, :category, :name, :address)
  end

  def find_item
    @item = Item.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
  end

  def create
    @review = Item.new(review_params)
    @booking = Booking.find(params[:booking_id])
    @item = @booking.item
    @review.booking = @booking
    if @review.save
      redirect_to item_path(@item)
    else
      render :new
    end
  end

  def show

  end

  private

  def review_params
    params.require(:review).permit(:stars, :comment, :booking_id)
  end
  def find_review
    @review = Review.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ActionController::Base
    # skip_before_action :authenticate_user!, only: :home

    def index
        @users = User.all
    end
    
    def show
        @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookings/index.html.erb
<h1>Your booking history</h1>

<ul>
  <% @bookings.each do |booking| %>
    <li>You started renting this item on: <%= booking.booking_start %></li>
    <li>and you should return it on:<%= booking.booking_end %></li>
  <% end %>
</ul>

<div class="card-menu">
<div class="card-wrapper mx-5">
<% @bookings.each do |booking| %>
  <div class="card-product">
    <%= image_tag(booking.item.picture_url) %>
    <h2 class="text-primary"> <%= booking.item.name %></h2>
    <div class="card-product-infos">
    <p>You started renting this item on: <strong><%= booking.booking_start %></strong>, and you should return it on <strong> <%= booking.booking_end %></strong>. In total, you booked <%= booking.item.name %> for <%= (booking.booking_end - booking.booking_start).to_i%> days.</p>
      <p>Total cost: <%= (booking.booking_end - booking.booking_start).to_i * booking.item.price %> USD</p>
    </div>
  </div>
<% end %>
</div>
</div>



<%= link_to "Go to items page", items_path %>

app/views/bookings/new.html.erb
<%= form_for([@item, @booking]) do |f| %>
  <%= f.label :booking_start %>
  <%= f.date_select :booking_start %>
  <%= f.label :booking_end %>
  <%= f.date_select :booking_end %>
  <%#= f.datetime_select :booking_end %>
  <%= f.submit %>
<% end %> 

app/views/items/edit.html.erb
<%= render 'shared/form' %>

app/views/items/index.html.erb
<%= render 'shared/hero' %>
<h2 class="mx-5 my-3">See What Items are Available Near You</h2>
<div class="card-menu">
<div class="card-wrapper mx-5">
<% @items.each do |item| %>
  <div class="card-product">
    <a href="<%= item_url(item) %>"><%= image_tag(item.picture_url) %></a>
    <h2 class="text-primary"> <%= item.name %></h2>
    <div class="card-product-infos">
      <p class="text-primary">Category: <%= item.category %></p>
      <p>Price/day: <%= item.price %></p>
      <p>Deposit: <%= item.deposit %></p>
      <div>

      <p><i class="fas fa-user fa-xs"></i> <%= item.user.first_name %> <%= item.user.last_name %></p>
      </div>
    </div>
  </div>
<% end %>
<div class="block"></div>
<%= paginate @items %>
</div>
</div>

app/views/items/new.html.erb
<%= render 'shared/form' %>

app/views/items/show.html.erb
<h1>Product Details:</h1>
  <div class="card">
    <div class="row">
      <div class="col-md-6 text-center align-self-center"><%= image_tag(@item.picture_url) %></div>
      <div class="col-md-6 info">
        <div class="row title">
          <div class="col"><h2><%= @item.name%></h2> in <%= @item.category%>
</div>
          <div class="col text-right"><a href="#"><i class="fa fa-heart-o"></i></a></div>
        </div>
        <span class="fa fa-star checked"></span> <span class="fa fa-star checked"></span> <span class="fa fa-star checked"></span> <span class="fa fa-star checked"></span> <span class="fa fa-star-half-full"></span> <span id="reviews">15 Reviews</span>
        <div class="row price">
          <div class="row"><h3 class="mb-0 font-weight-semibold"><%= @item.price%> USD/day</h3></div></a>
          <p>Location: <%= @item.user.location%></p>
          <%= link_to "Book this item", new_item_booking_path(@item) %>
          <%= link_to "Back to item page", items_path %>
          <h2>See on map:</h2>
          <div id="map"
              style="width: 100%; height: 600px;"
              data-markers="<%= @marker.to_json %>"
              data-mapbox-api-key="<%= Rails.application.credentials.dig(:MAPBOX_API_KEY) %>"></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Goodies</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_form.html.erb
<%= simple_form_for @item do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :category %>
  <%= f.input :category, collection: ["house appliances", "electronics", "clothes", "sports"] %>
  <%= f.label :price %>
  <%= f.number_field :price %>
  <%= f.label :deposit %>
  <%= f.number_field :deposit %>
  <%= f.label :address %>
  <%= f.input :address, collection: ["Jingan", "Minhang", "Pudong", "Hongkou"] %>
  <%= f.label :picture_url %>
  <%= f.text_field :picture_url %>
  <%= f.submit %>
<% end %>

app/views/shared/_hero.html.erb
<div class="bg-dark-gray">
<div class="container">
  <div class="row flex-lg-row-reverse align-items-center">
    <div class="col-10 col-sm-8 col-lg-6">
    <%= video_tag "goodies-hero.mp4", autoplay: :autoplay, loop: :loop, muted: :muted %>
    </div>
    <div class="col-lg-6">
      <h1 class="display-5 fw-bold lh-1 mb-3">Goodies <br>
      Exchange <br>
      Rent & Share</h1>
      <p class="lead">Goodies is a new way to share things. Get your Goodies today!</p>
      <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <button type="button" class="btn btn-primary btn-lg px-4 me-md-2"><%= link_to "Sign up", new_user_session_path, class: "text-white text-decoration-none" %></button>
      </div>
    </div>
  </div>
  </div>
</div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon ">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "logo.jpg" %>
    <% end %>
    <%# <%= link_to "book a flat" flats_path(@flat) %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Browse", "/", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My bookings", bookings_path, class: "nav-link"%>




          </li>
          <li class="nav-item dropdown">
            <%= image_tag "user-icon", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1> see the items in user's page here</h1>

<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.first_name, user_path(user) %></li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h2><%= @user.first_name %></h2>
<p><%= @user.location %></p>
<p><%= @user.email %></p>
<% @user.items.each do |item|%>
    <a href="<%= item_url(item) %>"><%= image_tag(item.picture_url) %></a>
    <p>Category: <%= item.category %></p>
    <p>Price/day: <%= item.price %></p>
    <p>Deposit: <%= item.deposit %></p>
    <p>User: <%= item.user.first_name %> <%= item.user.last_name %></p>

<% end %>